// console.log("Hello, World!");
// console.log("This is a sample Node.js application.");
// console.log(" this,is the best method to learn node.js");
// let name = "John Doe";
// console.log(name);


// const age = 30;
// console.log(age);


// var isStudent = true;
// console.log(isStudent);


// let sentence =(`My name is ${name} and I am ${age} years old. Am I a student? ${isStudent}`);
// console.log(sentence);

// let a = 10;
// let b = 5;
// let sum = a + b;
// console.log(`The sum of ${a} and ${b} is: ${sum}`);
// let person = {
//     name:"dina",
//     age: 25,
//     isStudent: false
// };
// console.log(person);
// let s="divine"
// let t="joy"
// if(s === t) {
//     console.log("The strings are equal.");
// }
// if (s !== t) {
//     console.log("The strings are not equal.");
// }
// if(s==t) {
//     console.log("The strings are equal.");
// }
// if (s!=t) {
//     console.log(true)}else{
//     console.log(false);
// }
// if(s<=t) {
//     console.log("The first string is less than or equal to the second string.");
// }
// let i=0;
// while(i< 5
//     ){
//     console.log(i);
//     i--;
// }

// function greet(name) {
//     console.log(`Hello, ${name}!`);
// }
// greet("Alice");
// greet("Bob");

for(let stones=0; stones<=5; stones++){
    console.log(stones);
}
let age=30;
let bodycount= true;

if(age===30 && bodycount ===true){
    console.log("You are 30 years old and have a body count.");
}else{
    console.log("You are not 30 years old or do not have a body count.");
}
let password = "myPassword123";
let username = "myUsername";
if(password === "myPassword123" && username === "myUsername") {
    console.log("Login successful!");
}else {
    console.log("Invalid username or password.");
}

let fruits= "mango";
switch(fruits){
    case "apple":
        console.log("This is an apple.");
        break;
    case "banana":
        console.log("This is a banana.");
        break;
    case "mango":
        console.log("This is a mango.");
        break;
     case "orange":
        console.log("This is an orange.");
        break;  
        case "grape":
            console.log("This is a grape.");
            break;
     
     default:
        console.log("This is not a recognized fruit.");
     }
     function greet(classmate){
        console.log("Hello, " + classmate + "!");
     }
     greet("Alice");
     greet("Bob");

     let greekt =(a,b)=>{
     let sum = a + b;

     console.log(sum);
     }

     greekt(5, 10);
let a=2;
let b=3;
     const great=(username,password)=>{
        let sum = a+b;
        console.log(sum);
     }

     function grit(classmate){
        console.log(`Hello, ${classmate}`);
     }
     grit("joy");
     grit("jam");
